config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # resources :users, only: [:index] do
  # resources :api, only: [:index, :create]
  # end
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :create, :new, :destroy]
      resources :likes, only: [:create]
    end
  end
  # root "articles#index"
  root to: 'users#index'
  namespace :api do 
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create] do
          end
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, Post, public: true
    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can :read, Post, user: user
    can :manage, Post, user: user # only post owners can manage posts
    can :manage, Comment, user: user # only post owners can manage posts
    return unless user.role == 'admin' # additional permissions for administrators

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, foreign_key: 'post_id'
  belongs_to :user, foreign_key: :author_id

  validates :text, presence: true

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true, foreign_key: 'author_id'
  belongs_to :post, optional: true, foreign_key: 'post_id'

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true, foreign_key: 'author_id'
  has_many :comments, dependent: :destroy, inverse_of: :post, foreign_key: 'post_id', counter_cache: :comments_counter
  has_many :likes, dependent: :destroy, inverse_of: :post, foreign_key: :post_id, counter_cache: :likes_counter

  validates :title, presence: true, length: { minimum: 5, maximum: 250 }
  validates :text, presence: true, length: { minimum: 5, maximum: 1000 }

  after_create :counter_increment
  after_destroy :counter_decrement

  def counter_increment
    self.user.posts_counter += 1
    self.user.save
  end

  def counter_decrement
    self.user.posts_counter -= 1
    self.user.save
  end

  def show_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy, inverse_of: :user, foreign_key: 'author_id', counter_cache: :posts_counter
  has_many :comments, dependent: :destroy, inverse_of: :user, foreign_key: 'author_id'
  has_many :likes, through: :posts, dependent: :destroy

  validates :name, presence: true

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    :role == 'admin'
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
    def authenticate_user
        return unless request.headers['Authorization'].present?
    
        begin
          jwt_payload = JWT.decode(request.headers['Authorization'].split[1].remove('"'),
                                   Rails.application.secrets.secret_key_base).first
          @current_user_id = jwt_payload['id']
        rescue JWT::ExpiredSignature, JWT::VerificationError, JWT::DecodeError
          head :unauthorized
        end
      end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
    load_and_authorize_resource
  
    def index
      @user = User.find(params[:user_id])
      @post = @user.posts.find(params[:post_id])
      @comments = @post.comments.order('created_at')
      render json: @comments
    end
  
    def create
      post = Post.find(params[:post_id])
      comment = post.comments.new(Text: comment_params[:Text], user: current_user)
  
      if comment.save
        render json: comment, status: :created, location: comment
      else
        render json: comment.errors, status: :unprocessable_entity
      end
    end
  
    private
  
    def comment_params
      params.require(:data).permit(:Text)
    end
  end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
    load_and_authorize_resource
    def index
      @user = User.find(params[:user_id])
      @posts = @user.posts
      render json: @posts
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def route_not_found
    render file: 'public/404.html', status: :not_found, layout: false
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name bio photo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @user = User.includes(:comments).find(params[:user_id])
    @comments = @user.comments
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new

    render :new
  end

  def create
    @user = User.find(params[:user_id])
    @comment = @user.comments.new(comment_params)
    flash[:notice] = @comment.errors.full_messages.to_sentence.capitalize unless @comment.save

    redirect_to user_post_path(current_user, params[:post_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    @post.comments_counter -= 1
    @comment.destroy!
    @post.save!
    redirect_to user_post_path(current_user, params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author_id: @user.id)
    if @like.save
      redirect_to user_post_path(@user, params[:post_id])
    else
      render 'posts/show'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user: @user).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(post_params)
    if @post.save
      redirect_to user_posts_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to current_user
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<h2>Create a new comment</h2>

<%= form_with scope: :comment, url: user_post_comments_path(@post.user, @post), local: true do |f| %>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>

  <div class="actions">
    <%= f.submit "post comment" %>
  </div>

<% end %>

app/views/comments/_like_form.html.erb
<%= form_with scope: :like, url: user_post_likes_path(@post.user, @post), local: true do |f| %>
  <%= f.submit "Like" , class: "like" %>
    <% end %>

app/views/comments/index.html.erb
<div class="comments-container">
    <h2>Comments</h2>
    <div class="comments">
        <% @comments.each do |comment| %>
        <div class="comment">
            <div class="comment-body">
            <%= comment.text %>
            </div>
            <div class="comment-author">
         <h4>by: <strong><%= comment.user.name %></strong></h4>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogBloggy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "users", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "header", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="header">
   <div class="header-left">
    <h1 class="headline">Bloggy App</h1>
    <p class="punchline">This is where we tell stories</p>
    </div>
  <div class="sign-out-btn-div">
  <%= button_to "Sign out", destroy_user_session_path, class: "sign-out-btn", method: :delete if user_signed_in? %> 
  </div>
  </div>
  <div class="user-container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts-container">
    <div class="post-header">
        <div class="post-image-holder">
            <img src="<%= @user.photo %>" alt="user">
        </div>
            <div class="post-details">
                <h3><%= @user.name %></h3>
                <p>Posts: <%= @user.posts_counter || 0%></p>
        </div>
    </div>

    <% @posts.reverse.each_with_index do |post, index| %>
        <div class="post">
            <a href="/users/<%= @user.id %>/posts/<%= post.id %>"><h4>Post No: <%= index+1 %></h4></a>
                
            <h3><%= post.title %></h3>
            <p><%= post.text %></p>
            <div class="">
                <p>Comments: <%= post.comments_counter || 0 %></p>
                <p>Likes: <%= post.likes_counter || 0 %></p>

                <div class="comments">
                    <h3>Comments:</h3>
                    <% post.show_recent_comments.each do |comment| %>
                    <h3> <%= @user.name %> :</h3>  
                    <p><%= comment.text %></p> 
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
    <div class="new-post">
        <%= link_to "Create New Post", new_user_post_path(@user) %>
    </div>

</div>

app/views/posts/new.html.erb
<h3>Add New post</h3>
<%= form_with scope: :post, url: user_posts_path, local: true do |f| %>
<%= f.label :title %> <br>
  <%= f.text_field :title %> <br>
  <%= f.label :text %> <br>
  <%= f.text_area :text %> <br>  
  <%= f.submit "create Post" %>

<% end %>

app/views/posts/show.html.erb
 <div class="detiled-post-container">
    <div class="detailed-post-header">
        <h4><%= @post.title %> by: <%= @post.user.name %></h4>
        <span>Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></span> 
    </div>
    <div class="detailed-post-text">
        <p><%= @post.text %></p>
    </div>
    <div class="detailes-post-comments">
        <h4>Comments:</h4>
        <% if @post.comments.empty? %>
        <p>No comments yet</p>
        <% else %>
        <% @post.comments.each do |comment| %>
            <div class="comment">
             <p><%= comment.user.name %>:</p>
                <p><%= comment.text %></p>
                <% if can? :destroy, comment %>
                    <%= button_to 'Delete comment', "/users/#{params[:user_id]}/posts/#{@post.id}/comments/#{comment.id}", method: :delete %>
                <% end %>
            </div>
            <% end %>
        <% end %>
    </div>
    <div class="comment-form">
        <%= render partial: 'comments/form', locals: { post: @post } %>
    </div>
    <br>
    <div class="like-form">
        <%= render partial: 'comments/like_form', locals: { post: @post } %>
    </div>
    <br>
    <div class="back-button">
        <%= link_to "Back", user_posts_path %>
    </div>
    <div class="destroy-btn">
        <% if can? :destroy, @post %> 
        <%= button_to "Delete", user_post_path(@post), method: :delete %>
        <% end %>
    </div>

 </div> 

app/views/users/index.html.erb
 <div class="current-user">
    <p>Loged in as: <%= current_user.name %></p>
 </div>

 <% @users.each do |user| %>
 <div class="users-container">
    <div class="main-image-container">
        <img src="<%= user.photo %>" alt="user" >
    </div>

    <div class="user-details-container">
       <a class="user-link" href='/users/<%= user.id %>'><strong>Name</strong>: <%= user.name %></a><br>
        <h5>Posts: <%= user.posts_counter || 0 %></h5>
    </div>
<div>

<% end %>

app/views/users/show.html.erb
<div class="current-user">
    <p>Loged in as: <%= current_user.name %></p>
  </div>

<div class="user-container">
    <div class="user-header">
        <img src="<%= @user.photo %>" alt="photo">
        <h2><%= @user.name %></h2>
        <p>Total Post: <%= @user.posts_counter %></p>

    </div>

    <div class="user-bio">
        <p><%= @user.bio %></p>
    </div>

    <div class="user-posts">
        <div class="post-container">
            <% @user.three_recent_posts.reverse.each_with_index do |post, index| %>
                <div class="post">
                    <h4>Post No: <%= index+1 %></h4>
                    <h3><%= post.title %></h3>
                    <p><%= post.text %></p>
                    <div class="counters">
                    <h5>Comments: <%= post.comments_counter || 0 %></h5>
                    <h5>likes: <%= post.likes_counter || 0 %></h5>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
<a href="/users/<%= @user.id %>/posts" class="users-show__button">See all posts</a>
</div>